---
# handlers file for ansible-role-template
- name: enable vault-agent
  ansible.builtin.systemd:
    name: vault-agent
    state: reloaded
    enabled: true
    daemon_reload: true

- name: Ensure Vault Agent Service
  ansible.builtin.service:
    name: vault-agent
    state: started
